package triggerflow.common;

import java.util.Objects;

/**
 * Deduplication key combining event identity and type.
 *
 * <p>Two events are considered duplicates if and only if they share the same
 * {@code eventId} and {@code eventType}. The deterministic {@code hashCode()}
 * generated by the record ensures consistent distribution across hash-based
 * data structures (Bloom filters, ConcurrentHashMaps).
 *
 * @param eventId   unique identifier of the event
 * @param eventType the type/category of the event
 */
public record EventKey(String eventId, String eventType) {

    public EventKey {
        Objects.requireNonNull(eventId, "eventId");
        Objects.requireNonNull(eventType, "eventType");
    }
}
